package com.palidinodh.rs.setting;

public enum SqlUserField {
  ID, NAME, PASSWORD, PASSWORD_SALT, EMAIL, IP_ADDRESS, MAIN_GROUP, SUB_GROUPS, PREMIUM_EXPIRATION, PENDING_BONDS, PENDING_VOTE_POINTS, VOTE_TIME_RUNELOCUS
}
