package com.palidinodh.rs.setting;

public enum SqlUserRank {
  UNKNOWN,
  BANNED,
  FORUM_MODERATOR,
  TRIAL_MODERATOR,
  MODERATOR,
  SENIOR_MODERATOR,
  ADMINISTRATOR,
  ADVERTISEMENT_MANAGER,
  COMMUNITY_MANAGER,
  YOUTUBER,
  BETA_TESTER,
  PREMIUM_MEMBER,
  DONATOR,
  SUPER_DONATOR,
  EXTREME_DONATOR,
  LEGENDARY_DONATOR,
  UBER_DONATOR
}
