package com.palidinodh.osrsscript.world.pvptournament;

import com.palidinodh.osrscore.io.cache.ItemId;
import com.palidinodh.osrscore.model.item.ItemDef;
import lombok.var;

public class DonatableItems {
  private static final int[] IDS = {ItemId.COINS, ItemId.BOND_32318, ItemId.AHRIMS_HOOD,
      ItemId.AHRIMS_STAFF, ItemId.AHRIMS_ROBETOP, ItemId.AHRIMS_ROBESKIRT, ItemId.DHAROKS_HELM,
      ItemId.DHAROKS_GREATAXE, ItemId.DHAROKS_PLATEBODY, ItemId.DHAROKS_PLATELEGS,
      ItemId.GUTHANS_HELM, ItemId.GUTHANS_WARSPEAR, ItemId.GUTHANS_PLATEBODY,
      ItemId.GUTHANS_CHAINSKIRT, ItemId.KARILS_COIF, ItemId.KARILS_CROSSBOW,
      ItemId.KARILS_LEATHERTOP, ItemId.KARILS_LEATHERSKIRT, ItemId.TORAGS_HELM,
      ItemId.TORAGS_HAMMERS, ItemId.TORAGS_PLATEBODY, ItemId.TORAGS_PLATELEGS, ItemId.VERACS_HELM,
      ItemId.VERACS_FLAIL, ItemId.VERACS_BRASSARD, ItemId.VERACS_PLATESKIRT, ItemId.ZENYTE_BRACELET,
      ItemId.ZENYTE_NECKLACE, ItemId.ZENYTE_RING, ItemId.ZENYTE_AMULET, ItemId.TORMENTED_BRACELET,
      ItemId.NECKLACE_OF_ANGUISH, ItemId.RING_OF_SUFFERING, ItemId.AMULET_OF_TORTURE,
      ItemId.ONYX_RING, ItemId.ONYX_NECKLACE, ItemId.ONYX_AMULET, ItemId.ONYX_BRACELET,
      ItemId.RING_OF_STONE, ItemId.AMULET_OF_FURY, ItemId.BERSERKER_NECKLACE, ItemId.REGEN_BRACELET,
      ItemId.ARMADYL_CROSSBOW, ItemId.STAFF_OF_THE_DEAD, ItemId.ARMADYL_GODSWORD,
      ItemId.BANDOS_GODSWORD, ItemId.SARADOMIN_GODSWORD, ItemId.ZAMORAK_GODSWORD,
      ItemId.ZAMORAKIAN_SPEAR, ItemId.ARMADYL_HELMET, ItemId.ARMADYL_CHESTPLATE,
      ItemId.ARMADYL_CHAINSKIRT, ItemId.BANDOS_CHESTPLATE, ItemId.BANDOS_TASSETS,
      ItemId.BANDOS_BOOTS, ItemId.SARADOMIN_SWORD, ItemId.SARADOMINS_TEAR, ItemId.KRAKEN_TENTACLE,
      ItemId.DRAGONFIRE_SHIELD_11284, ItemId.ELYSIAN_SPIRIT_SHIELD, ItemId.SPECTRAL_SPIRIT_SHIELD,
      ItemId.ARCANE_SPIRIT_SHIELD, ItemId.BLESSED_SPIRIT_SHIELD, ItemId.ABYSSAL_WHIP,
      ItemId.DARK_BOW, ItemId.OCCULT_NECKLACE, ItemId.ETERNAL_BOOTS, ItemId.PEGASIAN_BOOTS,
      ItemId.PRIMORDIAL_BOOTS, ItemId.LIGHT_BALLISTA, ItemId.LIGHT_BALLISTA, ItemId.HEAVY_BALLISTA,
      ItemId.MAGES_BOOK, ItemId.MASTER_WAND, ItemId.INFINITY_TOP, ItemId.INFINITY_HAT,
      ItemId.INFINITY_BOOTS, ItemId.INFINITY_GLOVES, ItemId.INFINITY_BOTTOMS, ItemId.ODIUM_WARD,
      ItemId.MALEDICTION_WARD, ItemId.TANZANITE_FANG, ItemId.TOXIC_BLOWPIPE_EMPTY,
      ItemId.SERPENTINE_VISAGE, ItemId.SERPENTINE_HELM_UNCHARGED, ItemId.MAGIC_FANG,
      ItemId.TOME_OF_FIRE_EMPTY, ItemId.DRAGON_WARHAMMER, ItemId.KODAI_WAND,
      ItemId.SARADOMINS_LIGHT, ItemId.ABYSSAL_BLUDGEON, ItemId.ABYSSAL_DAGGER,
      ItemId.ABYSSAL_DAGGER_P, ItemId.ABYSSAL_DAGGER_P_PLUS, ItemId.ABYSSAL_DAGGER_P_PLUS_PLUS,
      ItemId.BLACK_MASK_10, ItemId.BLACK_MASK, ItemId.SEERS_RING, ItemId.ARCHERS_RING,
      ItemId.WARRIOR_RING, ItemId.BERSERKER_RING, ItemId.DRAGON_AXE, ItemId.UNCUT_ONYX, ItemId.ONYX,
      ItemId.ZENYTE, ItemId.UNCUT_ZENYTE, ItemId.CRYSTAL_SEED, ItemId.NEW_CRYSTAL_BOW,
      ItemId.NEW_CRYSTAL_SHIELD, ItemId.DRAGON_PICKAXE, ItemId.TRIDENT_OF_THE_SEAS_FULL,
      ItemId.UNCHARGED_TRIDENT, ItemId.RING_OF_THE_GODS, ItemId.TYRANNICAL_RING,
      ItemId.TREASONOUS_RING, ItemId.DRAGON_CHAINBODY, ItemId.SMOKE_BATTLESTAFF,
      ItemId.MYSTIC_SMOKE_STAFF, ItemId.PRIMORDIAL_CRYSTAL, ItemId.PEGASIAN_CRYSTAL,
      ItemId.ETERNAL_CRYSTAL, ItemId.SMOULDERING_STONE, ItemId._3RD_AGE_RANGE_TOP,
      ItemId._3RD_AGE_RANGE_LEGS, ItemId._3RD_AGE_RANGE_COIF, ItemId._3RD_AGE_VAMBRACES,
      ItemId._3RD_AGE_ROBE_TOP, ItemId._3RD_AGE_ROBE, ItemId._3RD_AGE_MAGE_HAT,
      ItemId._3RD_AGE_AMULET, ItemId._3RD_AGE_PLATELEGS, ItemId._3RD_AGE_PLATEBODY,
      ItemId._3RD_AGE_FULL_HELMET, ItemId._3RD_AGE_KITESHIELD, ItemId._3RD_AGE_WAND,
      ItemId._3RD_AGE_BOW, ItemId._3RD_AGE_LONGSWORD, ItemId._3RD_AGE_CLOAK, ItemId._3RD_AGE_AXE,
      ItemId._3RD_AGE_PICKAXE, ItemId.DEXTEROUS_PRAYER_SCROLL, ItemId.ARCANE_PRAYER_SCROLL,
      ItemId.DRAGON_SWORD, ItemId.DRAGON_HARPOON, ItemId.DRAGON_THROWNAXE, ItemId.TWISTED_BUCKLER,
      ItemId.DRAGON_HUNTER_CROSSBOW, ItemId.DINHS_BULWARK, ItemId.ANCESTRAL_HAT,
      ItemId.ANCESTRAL_ROBE_TOP, ItemId.ANCESTRAL_ROBE_BOTTOM, ItemId.DRAGON_CLAWS,
      ItemId.ELDER_MAUL, ItemId.KODAI_INSIGNIA, ItemId.TWISTED_BOW, ItemId.AVERNIC_DEFENDER_HILT,
      ItemId.JUSTICIAR_FACEGUARD, ItemId.JUSTICIAR_CHESTGUARD, ItemId.JUSTICIAR_LEGGUARDS,
      ItemId.GHRAZI_RAPIER, ItemId.SANGUINESTI_STAFF_UNCHARGED, ItemId.SCYTHE_OF_VITUR_UNCHARGED,
      ItemId.UNCHARGED_TRIDENT_E, ItemId.UNCHARGED_TOXIC_TRIDENT_E, ItemId.VIGGORAS_CHAINMACE_U,
      ItemId.CRAWS_BOW_U, ItemId.THAMMARONS_SCEPTRE_U, ItemId.AMULET_OF_AVARICE,
      ItemId.VESTAS_SPEAR, ItemId.VESTAS_LONGSWORD, ItemId.VESTAS_CHAINBODY,
      ItemId.VESTAS_PLATESKIRT, ItemId.STATIUSS_WARHAMMER, ItemId.STATIUSS_FULL_HELM,
      ItemId.STATIUSS_PLATEBODY, ItemId.STATIUSS_PLATELEGS, ItemId.MORRIGANS_THROWING_AXE,
      ItemId.MORRIGANS_JAVELIN, ItemId.MORRIGANS_COIF, ItemId.MORRIGANS_LEATHER_BODY,
      ItemId.MORRIGANS_LEATHER_CHAPS, ItemId.ZURIELS_STAFF, ItemId.ZURIELS_HOOD,
      ItemId.ZURIELS_ROBE_TOP, ItemId.ZURIELS_ROBE_BOTTOM, ItemId.DRAGON_HASTA,
      ItemId.DRAGON_HASTA_P_PLUS_PLUS, ItemId.DRAGON_KNIFE, ItemId.BOOTS_OF_BRIMSTONE,
      ItemId.DEVOUT_BOOTS, ItemId.DRAKES_CLAW, ItemId.DRAKES_TOOTH, ItemId.HYDRAS_CLAW,
      ItemId.BRIMSTONE_RING, ItemId.DRAGON_HUNTER_LANCE, ItemId.HYDRA_LEATHER, ItemId.HYDRA_TAIL,
      ItemId.RING_OF_3RD_AGE, ItemId._3RD_AGE_PLATESKIRT, ItemId._3RD_AGE_DRUIDIC_ROBE_TOP,
      ItemId._3RD_AGE_DRUIDIC_ROBE_BOTTOMS, ItemId._3RD_AGE_DRUIDIC_STAFF,
      ItemId._3RD_AGE_DRUIDIC_CLOAK, ItemId.CRYSTAL_TOOL_SEED, ItemId.CRYSTAL_ARMOUR_SEED,
      ItemId.BLADE_OF_SAELDOR_INACTIVE, ItemId.DRAGONSTONE_FULL_HELM, ItemId.DRAGONSTONE_PLATEBODY,
      ItemId.DRAGONSTONE_PLATELEGS, ItemId.DRAGONSTONE_BOOTS, ItemId.DRAGONSTONE_GAUNTLETS};

  public static boolean isDonatable(int itemId) {
    if (itemId == -1) {
      return false;
    }
    for (var donatableId : IDS) {
      if (itemId == donatableId || ItemDef.getUnnotedId(itemId) == donatableId) {
        return true;
      }
    }
    return false;
  }
}
